title: Xuanhe Fan's Homepage
page-top-title: Xuanhe Fan
top-section-bg-text: Control Science
home-subtitle: Xuanhe  Fan&ensp;|&ensp;范烜赫
copyright-text: '&copy; Xuanhe Fan 2017-2026. All Rights Reserved.'
